### ISSUE TITLE
Error While Installing CLI on Linux

### ISSUE THREAD

**Issue by grichardomi** [run-x/opta#380]
Welcome to the opta installer.
Determining latest version
Going to install opta v0.14.7
Downloading installation package...
Downloaded
Installing...
/bin/bash: line 60: unzip: command not found
chmod: cannot access '/root/.opta/opta': No such file or directory
Successfully installed! Now you can run it via invoking /root/.opta/opta

**Comment by bigbitbus** [comment]
Hi, can you try to install unzip on your PC and retry?

Something like so (Ubuntu)
` sudo apt-get install unzip`

**Comment by grichardomi** [comment]
After installation, I get the following errors:
# opta apply
No command 'opta' found, did you mean:
 Command 'opt' from package 'llvm' (universe)
opta: command not found

**Comment by bigbitbus** [comment]
Opta is available at in your home directory at `~/.opta/opta` so you can add that to your Linux path and try, or simply invoke opta from ~/.opta/opta

**Comment by grichardomi** [comment]
Getting error:

[29058] Error loading Python lib '/root/.opta/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /root/.opta/libpython3.8.so.1.0)

**Comment by bigbitbus** [comment]
Which version of Linux are you using? What is the environment (docker container/VM/cloud etc.?)

**Comment by grichardomi** [comment]
16.04

**Comment by bigbitbus** [comment]
The Glibc library is outdated in 16.04; Is trying Ubuntu 20.04 at all an option?

**Comment by grichardomi** [comment]
Yes, it is. Will try it, thanks

**Comment by bigbitbus** [comment]
Sounds good. If you need more help/getting started/questions then please reach out to the contributors in our slack channel at: slack.opta.dev

**Comment by bigbitbus** [comment]
@grichardomi are you able to install successfully? If so, please close this issue...thanks!
