### ISSUE TITLE
Add VictoriaMetrics to integration list

### ISSUE THREAD

**Issue by denisgolius** [run-x/opta#382]
Hi there!

I see that you have support Prometheus integration on https://www.runx.dev/integrations
My question is, what about to add [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics) to integration list because it support PromQL but have many other features in [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) and [improvements](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#prominent-features)?

**Comment by legalosLOTR** [comment]
Hey @denisgolius, thanks for the suggestion. We will add it to our backlog - but it's not a high priority for us right now. If we hear a lot of potential users asking for it - we will move it up. Thanks!
