### ISSUE TITLE
OPTA doesn't delete the S3 bucket that created

### ISSUE THREAD

**Issue by anmyachev** [run-x/opta#633]
#### What happened:

An error occurred while calling the command: `opta apply -c flyte/opta/aws/env.yaml`.

<details><summary>Error</summary>

```bash
ERROR: An error occurred (AccessDenied) when calling the PutPublicAccessBlock operation: Access Denied
Traceback (most recent call last):
  File "opta/core/terraform.py", line 808, in _create_aws_state_storage
  File "botocore/client.py", line 391, in _api_call
  File "botocore/client.py", line 719, in _make_api_call
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the GetBucketEncryption operation: The specified bucket does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "opta/cli.py", line 66, in <module>
  File "click/core.py", line 1128, in __call__
  File "click/core.py", line 1053, in main
  File "click/core.py", line 1659, in invoke
  File "click/core.py", line 1395, in invoke
  File "click/core.py", line 754, in invoke
  File "opta/commands/apply.py", line 105, in apply
  File "opta/commands/apply.py", line 182, in _apply
  File "opta/core/terraform.py", line 935, in create_state_storage
  File "opta/core/terraform.py", line 851, in _create_aws_state_storage
  File "botocore/client.py", line 391, in _api_call
  File "botocore/client.py", line 719, in _make_api_call
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutPublicAccessBlock operation: Access Denied
Unhandled error encountered -- a crash report zipfile has been createded for you. If you need more help please reach out (passing the crash report) to the contributors in our slack channel at: https://slack.opta.dev

```

</details>

After that I use the command to destroy the created resources: `opta destroy -c flyte/opta/aws/env.yaml`
Output: `The opta state could not be found. This may happen if destroy ran successfully before.`

However, using the AWS web interface, I see that the bucket created by the opta remains. It's kind of a resource leaking.

#### What you expected to happen:

I expect that regardless of the success of the previous command, it is possible to delete all created resources.

#### Environment:
- Opta version (use `opta version`): `v0.24.3`
- Cloud provider (or hardware configuration for local): `AWS`
- OS (e.g: `cat /etc/os-release`): `Ubuntu 20.04.3 LTS`
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by NitinAgg** [comment]
@anmyachev Can you upload the crash report which was generated during the first failure due to permissions issue?

**Comment by anmyachev** [comment]
> @anmyachev Can you upload the crash report which was generated during the first failure due to permissions issue?

@NitinAgg thanks for quick response! Sure.
[opta_crash_report.zip](https://github.com/run-x/opta/files/7953293/opta_crash_report.zip)

**Comment by juandiegopalomino** [comment]
@anmyachev we found the reason and it's because our bucket creation is multi-step due to the AWS API and we were not handling errors in the middle gracefully. We'll add a fix shortly, but in the mean time you should be able to move forward by either manually deleting the bucket and waiting a few minutes (because S3 is eventually consistent), or by changing the name of the environment (and deleting the current bucket)

**Comment by anmyachev** [comment]
@juandiegopalomino thanks!

**Comment by anmyachev** [comment]
Guys, is it really necessary to apply the `"aws_s3_bucket_public_access_block"` restrictions to the bucket?
A private bucket seems to be created even without these restrictions...

**Comment by juandiegopalomino** [comment]
Following up in your other issue

**Comment by legalosLOTR** [comment]
This bug should be fixed once https://github.com/run-x/opta/issues/636 is fixed. So closing this one.
