### ISSUE TITLE
Delete information about the account id, in the process of generation `opta_crash_report.zip`

### ISSUE THREAD

**Issue by anmyachev** [run-x/opta#635]
#### Why is this needed:

This is sensitive information, I'd rather not share it.

### Extra info (e.g. existing slack convo link):

**Comment by legalosLOTR** [comment]
Hey! Thanks for catching that. We will do an audit of the information we record and obfuscate sensitive stuff.

**Comment by juandiegopalomino** [comment]
This has been done and will be made available on the next release!
