### ISSUE TITLE
 is it really necessary to apply the "aws_s3_bucket_public_access_block" restrictions to s3 buckets?

### ISSUE THREAD

**Issue by anmyachev** [run-x/opta#636]
Places where these permissions are needed:
- https://github.com/run-x/opta/blob/634d9b81d823f6a3d2a672421e5025ba032e630e/modules/aws_base/tf_module/log_bucket.tf#L45
- https://github.com/run-x/opta/blob/aa2cbd4e9848be1562dcca194a6340498789ace4/modules/aws_s3/tf_module/replication.tf#L107
- https://github.com/run-x/opta/blob/fc4b1ac4b331c6a7f9ce96ea5ea610cf5c80b035/modules/aws_s3/tf_module/bucket.tf#L91
- https://github.com/run-x/opta/blob/634d9b81d823f6a3d2a672421e5025ba032e630e/opta/core/terraform.py#L757

My problem is that I can't get those permissions.

Is it possible to get rid of this code and just create private buckets? For example, via `acl = "private"` https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#private-bucket-w-tags
It is not very clear why the bucket should not be able to be public at all...

**Comment by juandiegopalomino** [comment]
We need this to keep Opta using the best security practices. One of the thing Opta takes great pride in is making sure that your environments are secure, passing most standard compliance tests. We do most of our checks thanks to [regula by fugue](https://github.com/fugue/regula). One of the things that their initial tests complained about is that they wanted these blocks: https://docs.fugue.co/FG_R00229.html

Reading their logic, it appears pretty sound, and we simply shrugged at it as a "good practice". The fact that some folks may not have the needed permission is something that we are now going to think about. 

In the mean time, if you want help setting up the permission, please reach out to us in our slack and we'll be happy to walk you through it. If it's a "bureaucratic" then perhaps mention to them that this is needed to ensure the environment is compliant (which is true). Again, I am very sorry for the trouble, and I'll keep you posted on our thoughts on this.

**Comment by anmyachev** [comment]
@juandiegopalomino Thanks a lot for the explanation! I will try to find out why my account has such restrictions. I wonder how other users have :)

Have you considered making this step optional?

**Comment by anmyachev** [comment]
I found out a little. These permissions allow to change settings both at the bucket level and at the account-wide level. On our account, such permissions are blocked, which in turn blocks the possibility of applying them to a single bucket.

**Comment by juandiegopalomino** [comment]
`These permissions allow to change settings both at the bucket level and at the account-wide level.`
I think you're talking about PutAccountPublicAccessBlock, but you should only need PutBucketPublicAccessBlock

**Comment by anmyachev** [comment]
@juandiegopalomino not really, I mean that these settings will be applied to all buckets at once, and not just to the one created by the `flyte`. For an account in which several people work, such permissions are turned off so that users do not interfere with each other.

This can be found in the [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html) (Note section).

Note: "You can enable block public access settings only for access points, buckets, and AWS accounts. **Amazon S3 doesn't support block public access settings on a per-object basis**".

**Comment by legalosLOTR** [comment]
So just to clarify: The "block public access" can be applied at account-level or bucket-level. In Opta, we do it for the bucket-level ONLY - never at the account-level.

Based on your feedback, we have actually decided to get rid of these blocks completely. We will prioritize that in the next few weeks! Will keep you posted.

**Comment by juandiegopalomino** [comment]
Done and available on next release!

**Comment by brucearctor** [comment]
I see this marked as closed -- but where is the associated PR ( would be great practice to see linked/referenced in the issues that discuss )?
