### ISSUE TITLE
Error: release ingress-nginx failed, and has been uninstalled due to atomic being set: timed out waiting for the condition

### ISSUE THREAD

**Issue by anmyachev** [run-x/opta#650]
#### What happened:

`opta apply -c flyte.yaml --auto-approve` returned this error:

```bash

module.k8sbase.helm_release.ingress-nginx: Still creating... [5m0s elapsed]


╵
╷
│ Error: release ingress-nginx failed, and has been uninstalled due to atomic being set: timed out waiting for the condition
│
│   with module.k8sbase.helm_release.ingress-nginx,
│   on .opta/modules/aws_k8s_base/tf_module/ingress_nginx.tf line 2, in resource "helm_release" "ingress-nginx":
│    2: resource "helm_release" "ingress-nginx" {
│
╵
ERROR: Command '['exec', 'terraform', 'apply', '-compact-warnings', 'tf.plan']' returned non-zero exit status 1.
```

#### How to reproduce it (as minimally and precisely as possible):

I followed [this](https://docs.flyte.org/en/latest/deployment/aws/opta.html#deployment-aws-opta) instruction with two changes:

1. I deleted these lines from `env.yaml':
```bash
  - type: dns
    domain: <domain>
    delegated: false # set to true once ready https://docs.opta.dev/miscellaneous/ingress/
```
2. Made some changes suggested here: https://github.com/run-x/opta/issues/647#issuecomment-1025883498
#### Environment:
- Opta version (use `opta version`): `v0.24.3`
- Cloud provider (or hardware configuration for local): `AWS`
- OS (e.g: `cat /etc/os-release`): `Ubuntu 20.04`
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by juandiegopalomino** [comment]
@anmyachev Thank you again for the bug report. We feel terrible that you are running into so many and are very grateful of your issues. I know how frustrating and slow github issues back and forths can be, so if you'd like you're more than welcome join us on our public [slack](https://slack.opta.dev/) and we can dm there or even hop on a call if you'd like. Again, thank you so much for all of this feedback thus far.

**Comment by NitinAgg** [comment]
@anmyachev Sorry you ran into this issue. I ran the flyte's environment file with the changes you mentioned and it worked for me. Maybe there was some temporary network issue when you ran into this. Can you try running apply again and see if it works?

Unrelated: if you remove the `dns` module, [this](https://github.com/flyteorg/flyte/blob/master/opta/aws/flyte.yaml#L69) section of the flyte.yaml will break. Maybe hardcode it to be the load balancer uri you get from the environment.

**Comment by NitinAgg** [comment]
If you still face the issue, happy to help you in our slack at https://slack.opta.dev

**Comment by NitinAgg** [comment]
Terroform stores the state in a s3 bucket. But this is more likely due to some helm/k8s issue. If you are open to we can debug this over a video call?

**Comment by anmyachev** [comment]
@NitinAgg thanks! I will definitely open up to this, but let's do it a bit later :).

Could you tell a little about the debugging procedure in such cases? I think it will be helpful for others.

**Comment by NitinAgg** [comment]
Sure, so while the ingress is trying to apply, in separate terminal(s), you can try these commands:
* `watch kubectl get pods -A`
* `kubectl logs -n {NAMESPACE} {POD_NAME}` (namespace and pod_name from the list above)
* `kubectl get event -A -w`

**Comment by anmyachev** [comment]
Reinstalling opta of the same version + fixing s3 configs a little differently (regarding blocking public access) fixed the problem. Apparently I made some extra changes to the opta configs, that's why it didn't work. @NitinAgg thanks!
