### ISSUE TITLE
opta upgrade broken on fedora

### ISSUE THREAD

**Issue by loomsen** [run-x/opta#869]
#### What happened:
opta notified me of an available upade, upon running `opta upgrade`, it fails.

```
$ opta upgrade
Checking for version upgrades...
WARNING: New version available.
You have 0.30.2 installed. Latest version is 0.31.0.
Welcome to the opta installer.
Checking Prerequisites...
Opta would require (docker) to run properly. Please install these.
Determining latest version
curl: /home/nvarz/.opta/libcrypto.so.1.1: version `OPENSSL_1_1_1b' not found (required by /lib64/libssh.so.4)
curl: /home/nvarz/.opta/libcrypto.so.1.1: version `OPENSSL_1_1_1b' not found (required by /lib64/libk5crypto.so.3)
./opta_installation.sh: line 20: MAC_ADDRESS: unbound variable
Going to install opta v
Downloading installation package...
curl: /home/nvarz/.opta/libcrypto.so.1.1: version `OPENSSL_1_1_1b' not found (required by /lib64/libssh.so.4)
curl: /home/nvarz/.opta/libcrypto.so.1.1: version `OPENSSL_1_1_1b' not found (required by /lib64/libk5crypto.so.3)
curl: /home/nvarz/.opta/libcrypto.so.1.1: version `OPENSSL_1_1_1b' not found (required by /lib64/libssh.so.4)
curl: /home/nvarz/.opta/libcrypto.so.1.1: version `OPENSSL_1_1_1b' not found (required by /lib64/libk5crypto.so.3)
Version  not found.
Please check the available versions at https://github.com/run-x/opta/releases.
```

Using the way described in the docs works (more or less, there is an error from `mv` but apparently it's not critical):
```
$ VERSION=0.31.0 /bin/bash -c "$(curl -fsSL https://docs.opta.dev/install.sh)"
Welcome to the opta installer.
Checking Prerequisites...
Opta would require (docker) to run properly. Please install these.
Going to install opta v0.31.0
Downloading installation package...
Downloaded
Opta already installed. Overwrite? y
mv: cannot stat '/home/nvarz/.opta/local': No such file or directory

Installing...
mv: cannot stat '/tmp/opta_local/local': No such file or directory
Please symlink the opta binary to one of your path directories; for example using 'sudo ln -fs /home/nvarz/.opta/opta /usr/local/bin/opta'
Alternatively, you could add the .opta installation directory to your path like so
export PATH=$PATH:/home/nvarz/.opta
to your terminal profile.
```

#### What you expected to happen:
opta should upgrade itself to the latest version

#### How to reproduce it (as minimally and precisely as possible):
run `opta upgrade` from version `0.30.2`

#### Environment:
```json
{
  "opta_version": "0.30.2",
  "platform": "Linux",
  "os_name": "posix",
  "os_version": "#1 SMP PREEMPT Wed Apr 13 22:09:20 UTC 2022"
}
```

**Comment by juandiegopalomino** [comment]
@loomsen can't seem to reproduce-- ran fedora on my macbook via docker and the upgrade worked fine (yes, we know about the `mv: cannot stat '/tmp/opta_local/local': No such file or directory` issue, and it's benign and we're working on resolving it).
<img width="872" alt="Screen Shot 2022-05-16 at 4 23 50 PM" src="https://user-images.githubusercontent.com/10430635/168698020-7df06a24-cb4d-42d1-888b-afc10f9a618e.png">

**Comment by juandiegopalomino** [comment]
Have you tried the solution posted here? https://github.com/openssl/openssl/issues/5845

**Comment by juandiegopalomino** [comment]
Reproduced-- OK looks like the issue is with Fedora 35 and earlier has issues with the libcrypto.so.1.1 packaged by Opta (it was built on CentOS-- frankly the surprising part is that it starts failing here lol). @loomsen were there any other similar errors encountered on Opta usage in Fedora?

**Comment by loomsen** [comment]
Hey, I've only ever used it for generating terraform code, and haven't had any troubles with that part.
If it works in 36 I guess we can close this, as the other installation method (using `VERSION=0.31.0 /bin/bash -c "$(curl -fsSL https://docs.opta.dev/install.sh)"` works.
