### ISSUE TITLE
Expose the --image-tag command line parameter as a variable or output of the k8s-service module.

### ISSUE THREAD

**Issue by edeesis** [run-x/opta#887]
#### What would you like to be added:

I would like to be able to reference the `--image-tag` command line parameter as a variable in my Opta YAML.

I see that you can refer to the entire image name: https://docs.opta.dev/reference/aws/modules/aws-k8s-service/#outputs, but that's the entire image name, including the repo, where all I need is the tag.

#### Why is this needed:

Without this, you have to create a duplicitous input_variable.

**Comment by juandiegopalomino** [comment]
I don't think we'll be exposing the image tat as a possible variable (we're actually trying to have variables replace it down the line) but we can have the current tag as an output.

**Comment by edeesis** [comment]
Just to clarify, I was hoping to use the image tag as an environment variable in my k8s-service definition. Is that possible with it being an output?

**Comment by juandiegopalomino** [comment]
but we can keep this in consideration for the future

**Comment by edeesis** [comment]
If the decision going forward is to have image-tag be only a variable, not something Opta does implicitly, that's fine.

Currently, if we want to reference the image tag anywhere else in the YAML other than the k8s-service image, we have to use a variable.

**Comment by juandiegopalomino** [comment]
Done!
