### ISSUE TITLE
Support for the depends_on Terraform feature 

### ISSUE THREAD

**Issue by edeesis** [run-x/opta#893]
#### What would you like to be added:

Support for Terraform's [depends_on](https://www.terraform.io/language/meta-arguments/depends_on) feature.

#### Why is this needed:

Forcing terraform to create certain modules in the same manifest file before others, particularly for jobs and other applications that need to be up before the latest version of the application code can be put up. 

An example of this would be for database migrations. Migrations to add the new column should be run before the application code can query the database. While you can create a separate manifest to manage it, as described in the [docs](https://docs.opta.dev/features/jobs/db_migration/#in-a-one-time-job), that means you have to have reference to the database outside where the database is created and managed.

### Extra info (e.g. existing slack convo link):

https://opta-group.slack.com/archives/C0240NBKUMT/p1653326679695919?thread_ts=1653099767.603579&cid=C0240NBKUMT

**Comment by juandiegopalomino** [comment]
OK, will be in ~2 weeks

**Comment by juandiegopalomino** [comment]
done
