### ISSUE TITLE
Support for waits_for_job

### ISSUE THREAD

**Issue by edeesis** [run-x/opta#894]
#### What would you like to be added:

Helm Release has a [waits_for_job](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#wait_for_jobs) argument that will hold the terraform from completing until the jobs complete.

I would like to wait for jobs to complete before I deploy my k8s-service module.

#### Why is this needed:

When running migrations, you want the migrations to be complete before deploying your app code, otherwise your app could start querying a column that is not there yet, causing 500 errors.

### Extra info (e.g. existing slack convo link):

https://opta-group.slack.com/archives/C0240NBKUMT/p1653335558506789?thread_ts=1653099767.603579&cid=C0240NBKUMT

Related:

https://github.com/run-x/opta/issues/893

**Comment by juandiegopalomino** [comment]
OK, will be in ~2 weeks

**Comment by juandiegopalomino** [comment]
Done!
