### ISSUE TITLE
Do not require input variables in non apply/deploy commands on Opta CLI

### ISSUE THREAD

**Issue by lfvarela** [run-x/opta#907]
#### What happened:

I've noticed that all opta cli commands require you to pass input variables when they shouldn't be required.
For example, I have the following one in my service file:
input_variables:
  - name: github_sha
which ends up populating en env var.

#### What you expected to happen:

But if I want to shell into my running container with opta shell, see logs, etc, I shouldn't need to specify these, but the cli requires me to.

One option is to mark them as optional (put a sane default) but I want them to be required when applying / deploying the YAML but not for everything else.

#### Environment:
- Opta version (use `opta version`): 0.32.2
- Cloud provider (or hardware configuration for local):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by juandiegopalomino** [comment]
fix merged!
