### ISSUE TITLE
Ability to override command and args in K8s Service

### ISSUE THREAD

**Issue by edeesis** [run-x/opta#911]
#### What would you like to be added:

The K8s deployment API can override the ENTRYPOINT and CMD of the Docker image via the `command` and `args` properties on the ContainerSpec. The allows you to build 1 image with your application and deploy it with different commands. 

#### Why is this needed:

Without this, you have to build separate images for each command you want to use the same container, causing you to have to create multiple Docker repos or tag them differently.

### Extra info (e.g. existing slack convo link):

**Comment by juandiegopalomino** [comment]
done!
